baseURL = "https://namashin.github.io/"
languageCode = 'en-us'
title = '@namashin'
theme = "ananke"
publishDir = "docs"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[languages]
[languages.en]
languageName = "English"
weight = 1
contentDir = "content/en"

[languages.ja]
languageName = "日本語"
weight = 2
contentDir = "content/ja"

[languages.ch]
languageName = "中文"
weight = 3
contentDir = "content/ch"
