baseURL = "https://namashin.github.io/"
languageCode = "en-us"
title = "IKUMA NAGAHARA | Portfolio"
theme = "ananke"
publishDir = "docs"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

################################################################################
# English
################################################################################
[languages.en]
languageName = "English"
weight = 1
contentDir = "content/en"
languageCode = "en"

[languages.en.params]
name = "NAGAHARA IKUMA"
title = "Software Engineer"
description = "I build reliable, complex, and scalable software systems."
email = "mailto:changyuanshengzhen@icloud.com"
github = "https://github.com/namashin"
linkedin = "https://www.linkedin.com/in/namashin/"
resume = "/materials/NagaharaIkuma_Resume.pdf"

# == Introduce (EN) with four fields ==
[[languages.en.params.introduce]]
Introduction = """
Hello! My name is NAGAHARA IKUMA.
I am currently pursuing a Master’s degree in Software Engineering at East China Normal University in Shanghai, China.
I enjoy studying in an international environment alongside my Chinese classmates, which enriches my academic and cultural experiences
"""

Development = """
I have a passion for traveling and have visited several countries, including Taiwan, China, Hong Kong, Dubai, Italy, and South Korea.
These experiences have allowed me to explore diverse cultures and perspectives, which have greatly enhanced my intercultural understanding and broadened my horizons
"""

Turn = """
In my professional career, I worked for approximately two years at Pixel Software Corporation in Japan,
where I developed industrial real-time process information management systems and factory data management software.
Following that, I completed a remote internship at “Tomorrows AI” in the United States, where I contributed to media platform development
"""

Conclusion = """
Leveraging my multicultural experiences and technical skills,
I aspire to contribute to international projects and create innovative value as a professional engineer.
Thank you for your time, and I look forward to connecting with you.
"""

# == Experience ==
[[languages.en.params.experience]]
date = "2024.10 - 2024.12"
title = "Software Developer Intern - Tomorrows AI"
description = """
I contributed to the development of a media platform by building a Flask-based web application,
which enabled efficient keyword and title searches to enhance user experience.

I also designed and implemented a dynamic detail page to display article titles, images, and content retrieved from Flask data,
improving interactivity and user engagement. Working in a remote, international environment, I focused on clean code practices and performance optimization, ultimately helping to deliver a high-quality, scalable web solution
"""
skills = ["Python", "Flask", "JavaScript", "HTML", "CSS", "MySQL", "OpenAI API", "AWS"]
logo = "/icons/tomorrows_ai.jpg"
url = "https://www.tomorrowsai.org/"

[[languages.en.params.experience]]
date = "2023.9 - Present"
title = "Start Pursuing Master Degree - East China Normal University"
description = """
I relocated from Japan to Shanghai, China, to pursue a Master's degree in Software Engineering at East China Normal University.
This program has allowed me to delve into advanced software development and system architecture, while also fostering an international perspective through collaboration with peers from diverse backgrounds
"""
skills = ["Master Degree", "Software Engineering", "Chinese Government Full Scholarship Student"]
logo = "/icons/ecnu.jpg"
url = "https://english.ecnu.edu.cn/"
department = "Software Engineering Institute"
major = "Software Engineering"
gpa = "3.14/4.0"

[[languages.en.params.experience]]
date = "2021.4 - 2023.6"
title = "Software Engineer - Pixel Software 株式会社"
description = """
I developed an industrial gateway system using Golang and Python to replace legacy VB and C systems, significantly improving maintainability and scalability.
By optimizing Golang’s concurrency features, I successfully handled thousands of sensor tags, boosting data throughput by over 40% and reducing processing time.
I also programmed control software in C#, enabling system operators to monitor real-time industrial data. In collaboration with a seven-member team, I participated in software specification design, test plan execution, and quality assurance. Furthermore, I created detailed technical documentation, reported project progress, and provided solutions to stakeholders
"""
skills = ["Golang", "Python", "C#", ".NET", "SQL", "MySQL", "Microsoft Access", "TCP/IP"]
logo = "/icons/pixelsoft.jpg"
url = "http://www.pixelsoft.co.jp/pc/index.html"

[[languages.en.params.experience]]
date = "2019.9 - 2021.6"
title = "Graduated Bachelor Degree - Shanghai International Studies University"
description = """
I graduated with a Bachelor's degree in Teaching Chinese to Speakers of Other Languages from the School of Education at Shanghai International Studies University.
This academic background fostered a deep understanding of language learning and intercultural communication, which has proven invaluable in international academic and professional environments
"""
skills = ["Bachelor Degree", "Chinese"]
logo = "/icons/sisu.jpg"
url = "https://en.shisu.edu.cn/"
department = "School of Education"
major = "Teaching Chinese to Speakers of Other Languages"
gpa = "3.4/4.0"

# == Professional Skills ==
[[languages.en.params.professional_skills]]
category = "Programming Languages"
skills = ["Golang", "Python", "c-sharp", "JavaScript", "SQL", "HTML", "CSS"]

[[languages.en.params.professional_skills]]
category = "Frameworks"
skills = ["DotNET"]

[[languages.en.params.professional_skills]]
category = "Web Development"
skills = ["Gin", "Django", "Flask"]

[[languages.en.params.professional_skills]]
category = "Tools"
skills = ["Git", "GitHub", "Docker", "AWS"]

[[languages.en.params.professional_skills]]
category = "Operating Systems"
skills = ["Windows", "Linux"]

[[languages.en.params.professional_skills]]
category = "Other Technologies"
skills = ["TCPIP", "jQuery"]

# == Projects (English) ==
[[languages.en.params.projects]]
title = "China Eastern Airlines Dispatch Optimization"
period = "2024.9 - Present"
overview = """Participated in a dispatch optimization project at China Eastern Airlines to enhance task assignment and scheduling efficiency.
Utilized Deep Reinforcement Learning (CVNet) and swarm intelligence algorithms (ABC, FA) to develop a dispatch model adaptable to dynamic real-time environments"""
roles = """[Model Design]
- Modeled task assignment as a Semi-Markov Decision Process (SMDP), factoring in task priority, travel cost, and skill compatibility.
- Addressed combination constraints based on employee skills (A, B, C).

[Algorithm Implementation]
- Employed CVNet to learn the value function for tasks and optimize dynamic task assignment.
- Leveraged swarm intelligence algorithms (ABC, FA) to reduce travel costs while improving scheduling efficiency.

[Proposal of Results]
- Proposed research outcomes to China Eastern Airlines, including algorithm implementation details, performance evaluation, and practical applicability"""
results = """[Outcome]
- Proposed a new dispatch model that contributes to improved operational efficiency at China Eastern Airlines.
- Developed algorithms capable of real-time dynamic task adjustment.
- The proposal is designed with actual on-site application in mind"""

################################################################################
# Japanese
################################################################################
[languages.ja]
languageName = "日本語"
weight = 2
contentDir = "content/ja"
languageCode = "ja"

[languages.ja.params]
name = "長原生真"
title = "ソフトウェアエンジニア"
description = ""
email = "mailto:changyuanshengzhen@icloud.com"
github = "https://github.com/namashin"
linkedin = "https://www.linkedin.com/in/namashin/"
resume = "/materials/NagaharaIkuma_Resume.pdf"

# == Introduce (JA) with four fields ==
[[languages.ja.params.introduce]]
Introduction = """
現在、上海の華東師範大学でソフトウェア工学の修士課程を履修しています。大学卒業後、日本のPixel Software株式会社で約2年間勤務し、産業用リアルタイムプロセス情報管理システムや工場データ管理ソフトウェアを開発しました
"""

Development = """
その後、アメリカの「Tomorrows AI」でリモートインターンシップを完了し、メディアプラットフォームの開発に貢献しました。さまざまな文化や視点に触れることで、技術スキルだけでなく多角的な思考力も培うことができました
"""

Turn = """
台湾、中国本土、香港、ドバイ、イタリア、韓国など多くの国を旅し、各地域の価値観に触れることで、異なる文化の中でのコミュニケーションや問題解決能力を深めています
"""

Conclusion = """
こうした多文化体験と技術的専門性を活かし、国際的なプロジェクトに参加してイノベーションを創出したいと考えています。私の経歴を知っていただき、ありがとうございます。今後のご縁を楽しみにしております
"""

# == Experience ==
[[languages.ja.params.experience]]
date = "2024.10 - 2024.12"
title = "ソフトウェア開発インターン - Tomorrows AI"
description = """
メディアプラットフォーム向けのFlaskベースのWebアプリケーションを開発し、キーワード検索機能を効率化してユーザー体験を向上させました。Flaskから取得した記事タイトルや画像、コンテンツを動的に表示する詳細ページを設計・実装し、インタラクティブなユーザーエンゲージメントを促進しました。リモートの国際チームで連携し、パフォーマンス最適化とクリーンコードを重視した開発に取り組みました
"""
skills = ["Python", "Flask", "JavaScript", "HTML", "CSS", "MySQL", "OpenAI API", "AWS"]
logo = "/icons/tomorrows_ai.jpg"
url = "https://www.tomorrowsai.org/"

[[languages.ja.params.experience]]
date = "2023.9 - 現在"
title = "修士課程を開始 - 華東師範大学"
description = """
日本から中国上海に移り、華東師範大学でソフトウェア工学の修士課程を履修しています。先端的なソフトウェア設計やシステム構築を学びながら、多国籍な環境で国際的視野を養い、技術力とコミュニケーション能力の両面を伸ばしています
"""
skills = ["修士学位", "ソフトウェア工学"]
logo = "/icons/ecnu.jpg"
url = "https://english.ecnu.edu.cn/"
department = "ソフトウェア工学"
major = "ソフトウェア工学"
gpa = "3.14/4.0"

[[languages.ja.params.experience]]
date = "2021.4 - 2023.6"
title = "ソフトウェアエンジニア - Pixel Software 株式会社"
description = """
GolangとPythonを使用した産業監視システムを開発し、従来のVBおよびCシステムを置き換えて保守性と拡張性を大幅に向上させました。Goroutineの最適化により、大量のセンサーデータを効率的に処理し、処理速度を向上させています。また、C#による制御ソフトウェアの開発を通じて、操作員がリアルタイムで産業データを監視できる仕組みを提供しました。7人チームの一員として、設計からテストまで一連の開発工程に携わり、高品質なソフトウェアの納品に貢献しました
"""
skills = ["Golang", "Python", "C#", ".NET", "SQL", "MySQL", "Microsoft Access", "TCP/IP"]
logo = "/icons/pixelsoft.jpg"
url = "http://www.pixelsoft.co.jp/pc/index.html"

[[languages.ja.params.experience]]
date = "2019.9 - 2021.6"
title = "学士号取得 - 上海外国語大学"
description = """
上海外国語大学の教育学部を卒業し、中国語国際教育の学士号を取得しました。多文化間コミュニケーションや言語教育の知見を身につけ、異なる文化圏での学習や業務でも柔軟に対応できる基礎を築きました
"""
skills = ["学士学位", "中国語"]
logo = "/icons/sisu.jpg"
url = "https://en.shisu.edu.cn/"
department = "Education"
major = "Teaching Chinese to Speakers of Other Languages"
gpa = "3.4/4.0"

# == Professional Skills ==
[[languages.ja.params.professional_skills]]
category = "プログラミング言語"
skills = ["Golang", "Python", "c-sharp", "JavaScript", "SQL", "HTML", "CSS"]

[[languages.ja.params.professional_skills]]
category = "フレームワーク"
skills = ["DotNET"]

[[languages.ja.params.professional_skills]]
category = "Web開発"
skills = ["Gin", "Django", "Flask"]

[[languages.ja.params.professional_skills]]
category = "ツール"
skills = ["Git", "GitHub", "Docker", "AWS"]

[[languages.ja.params.professional_skills]]
category = "オペレーティングシステム"
skills = ["Windows", "Linux"]

[[languages.ja.params.professional_skills]]
category = "その他の技術"
skills = ["TCPIP", "jQuery"]

# == Projects (Japanese) ==
[[languages.ja.params.projects]]
title = "东方航空 派工最適化プロジェクト"
period = "2024.9 - 現在"
overview = """东方航空のタスク割り当てとスケジューリング効率を向上させるための派工最適化プロジェクトに参画。深層強化学習（CVNet）と群知能アルゴリズム（ABC、FA）を活用し、リアルタイムで動的な環境に適応可能な派工モデルを開発"""
roles = """【モデル設計】
・タスク割り当てを半マルコフ決定プロセス（SMDP）としてモデリングし、タスクの優先度、移動コスト、スキル適合性を考慮
・従業員のスキル（A、B、C）に基づく組み合わせ制約を解決

【アルゴリズム実装】
・CVNetを用いてタスクの価値関数を学習し、動的なタスク割り当てを最適化
・群知能アルゴリズム（ABC、FA）を活用して移動コストを削減しつつスケジュール効率を向上

【成果提案】
・プロジェクトを通じて得られた研究成果を东方航空に提案。アルゴリズムの実装方法、パフォーマンス評価、および実運用での適用可能性を含む
"""
results = """【成果】
・东方航空の運用効率向上に寄与する新しい派工モデルを提案
・リアルタイムのタスク動的調整が可能なアルゴリズムを開発
・提案内容は航空運用現場での実用化を前提に設計
"""

################################################################################
# Chinese
################################################################################
[languages.zh]
languageName = "中文"
weight = 3
contentDir = "content/zh"
languageCode = "zh"

[languages.zh.params]
name = "长原生真"
title = "软件工程师"
description = "我构建可靠、复杂且可扩展的软件系统。"
email = "mailto:changyuanshengzhen@icloud.com"
github = "https://github.com/namashin"
linkedin = "https://www.linkedin.com/in/namashin/"
resume = "/materials/NagaharaIkuma_Resume.pdf"

# == Introduce (ZH) with four fields ==
[[languages.zh.params.introduce]]
Introduction = """
您好！我叫长原生真，目前正在中国上海的华东师范大学攻读软件工程硕士学位。我喜欢在国际化的环境中与我的中国同学一起学习，这丰富了我的学术和文化体验
"""

Development = """
我热爱旅行，曾访问过台湾、中国、香港、迪拜、意大利和韩国等多个国家。这些经历让我能够探索多样的文化和视角，大大提升了我的跨文化理解能力，拓宽了我的视野
"""

Turn = """
在我的职业生涯中，我在日本的Pixel Software株式会社工作了大约两年，开发了工业实时过程信息管理系统和工厂数据管理软件。之后，我完成了在美国“Tomorrows AI”的远程实习，参与了媒体平台的开发
"""

Conclusion = """
利用我的多文化经验和技术技能，我希望能为国际项目做出贡献，作为一名专业工程师创造创新价值。感谢您的时间，期待与您联系
"""

# == Experience ==
[[languages.zh.params.experience]]
date = "2024.10 - 2024.12"
title = "软件开发实习生 - Tomorrows AI"
description = """
在远程团队环境中，基于Flask开发了媒体平台的Web应用程序，优化了用户体验和关键字搜索功能.
还设计并实现了动态详细页面以展示文章标题、图片和内容，从而提升了交互性和用户参与度。注重代码质量和性能优化，与国际化团队合作，高效完成了平台的核心功能.
"""
skills = ["Python", "Flask", "JavaScript", "HTML", "CSS", "MySQL", "OpenAI API", "AWS"]
logo = "/icons/tomorrows_ai.jpg"
url = "https://www.tomorrowsai.org/"

[[languages.zh.params.experience]]
date = "2023.9 - 现在"
title = "开始攻读硕士学位 - 华东师范大学"
description = """
从日本搬到中国上海，在华东师范大学攻读软件工程硕士学位。深入学习软件开发、系统设计及前沿技术，并在国际化环境中拓展多元化的学术和实践经验，为未来从事跨国项目奠定了扎实的基础
"""
skills = ["硕士学位", "软件工程", "中国政府奖学金生"]
logo = "/icons/ecnu.jpg"
url = "https://english.ecnu.edu.cn/"
department = "软件工程学院"
major = "软件工程"
gpa = "3.14/4.0"

[[languages.zh.params.experience]]
date = "2021.4 - 2023.6"
title = "软件工程师 - Pixel Software 株式会社"
description = """
我使用Golang开发了一套从工厂内的传感器实时收集数据并将其传递到前端的网关系统.
在这个系统中，通过使用TCP/IP协议从传感器获取数据，并利用Golang的并发处理功能（goroutines和channels）高效处理大量数据.
通过这一技术优化，从原本基于VB和C语言的遗留系统成功迁移，不仅将数据吞吐量提升了40%，还显著缩短了处理时间.

此外，我设计了RESTful API，实现了与前端的顺畅对接。该API不仅确保了数据获取的实时性，还撰写了详细的API规范文档，并在开发团队内进行了共享和讨论.
API的端点设计灵活，可以根据传感器ID和数据类型进行过滤，方便前端团队轻松获取所需数据
"""
skills = ["Golang", "Python", "C#", ".NET", "SQL", "MySQL", "Microsoft Access", "TCP/IP"]
logo = "/icons/pixelsoft.jpg"
url = "http://www.pixelsoft.co.jp/pc/index.html"

[[languages.zh.params.experience]]
date = "2019.9 - 2021.6"
title = "获得学士学位 - 上海外国语大学"
description = """
在上海外国语大学国际教育学院获得汉语国际教育学士学位，系统学习了语言教学与跨文化交流的理论与实践，为在多元文化环境中从事开发与沟通工作奠定了坚实的语言与文化基础
"""
skills = ["学士学位", "汉语", "教育"]
logo = "/icons/sisu.jpg"
url = "https://en.shisu.edu.cn/"
department = "国际教育学院"
major = "汉语国际教育"
gpa = "3.4/4.0"

# == Professional Skills ==
[[languages.zh.params.professional_skills]]
category = "编程语言"
skills = ["Golang", "Python", "c-sharp", "JavaScript", "SQL", "HTML", "CSS"]

[[languages.zh.params.professional_skills]]
category = "框架"
skills = ["DotNET"]

[[languages.zh.params.professional_skills]]
category = "Web开发"
skills = ["Gin", "Django", "Flask"]

[[languages.zh.params.professional_skills]]
category = "工具"
skills = ["Git", "GitHub", "Docker", "AWS"]

[[languages.zh.params.professional_skills]]
category = "操作系统"
skills = ["Windows", "Linux"]

[[languages.zh.params.professional_skills]]
category = "其他技术"
skills = ["TCPIP", "jQuery"]

# == Projects (Chinese) ==
[[languages.zh.params.projects]]
title = "东方航空 派工优化项目"
period = "2024.9 - 至今"
overview = """参与东方航空的派工优化项目，以提高任务分配和调度效率。
使用深度强化学习（CVNet）和群智能算法（ABC、FA），开发可适应实时动态环境的派工模型"""
roles = """【模型设计】
- 将任务分配建模为半马尔可夫决策过程（SMDP），考虑任务优先级、移动成本和技能适配性
- 基于员工技能（A、B、C）解决组合约束

【算法实现】
- 采用CVNet学习任务价值函数，优化动态任务分配
- 利用群智能算法（ABC、FA）在降低移动成本的同时提升调度效率

【成果提案】
- 向东方航空提出项目研究成果，包括算法实现细节、性能评估及实际运用的可行性
"""
results = """【成果】
- 提出新的派工模型，为东方航空的运营效率提高做出贡献
- 开发可实现实时动态任务调整的算法
- 设计方案充分考虑航空运营一线的实际应用需求
"""